name: Starting a new work item

on:
    project_card:
        types: [moved]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Check move from "TODO" to "IN PROGRESS"
            id: check
            uses: prishanf/salesforcedx-kanban-actions/project_card-check-movement@master
            with:
                token: ${{ secrets.GITHUB_TOKEN}}
                fromColumnId: ${{ github.event.changes.column_id.from }}
                fromColumnName: TODO
                toColumnId: ${{ github.event.project_card.column_id }}
                toColumnName: IN PROGRESS
          - name: Check out the source code
            uses: actions/checkout@v2
          - name: Authorize Dev Hub
            uses: sfdx-actions/setup-sfdx@v1
            with:
              sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
            if: steps.check.outputs.isMatch == 'true'
          - name: Create Scratch Org
            uses: forcedotcom/salesforcedx-actions@master
            with:
              args: sfdx force:org:create -v ${{ secrets.USERNAME }} -s -f config/project-scratch-def.json -a
            if: steps.check.outputs.isMatch == 'true'
            - name: Create user
            uses: forcedotcom/salesforcedx-actions@master
            with:
              args: force:user:create --definitionfile=config/user-def.json --setalias=new-user
          - name: Change password
            uses: forcedotcom/salesforcedx-actions@master
            with:
              args: force:user:password:generate --targetusername=new-user
          - name: Display user information
            id: display_user
            uses: forcedotcom/salesforcedx-actions@master
            with:
              args: force:user:display --targetusername=new-user --json
          - name: Display open url
            id: display_url
            uses: forcedotcom/salesforcedx-actions@master
            with:
              args: force:org:open --urlonly --targetusername=new-user --json
          - name: install gmail-send
            run: npm install --save gmail-send
            if: steps.check.outputs.isMatch == 'true'
          - name: Send Email vi Gmail
            uses: prishanf/sendgrid-action@master
            env:
                DISPLAY_USER_JSON: '{"result": {"orgId":"ABC","username":"Prishan","instanceUrl":"www.google.com","loginUrl":"/login"}}'
                DISPLAY_URL_JSON: '{"result": {"url":"/abcd"}}'
                SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
                GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
                EMAIL_TO: ${{ secrets.EMAIL_TO }}
                GMAIL_FROM: ${{ secrets.GMAIL_FROM }}
                SCRIPT_FILEPATH: scripts/email.js
            if: steps.check.outputs.isMatch == 'true'
            
