name: Starting a new work item

on:
    project_card:
        types: [moved]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Check move from "TODO" to "IN PROGRESS"
            id: check
            uses: prishanf/salesforcedx-kanban-actions/project_card-check-movement@master
            with:
                token: ${{ secrets.GITHUB_TOKEN}}
                fromColumnId: ${{ github.event.changes.column_id.from }}
                fromColumnName: TODO
                toColumnId: ${{ github.event.project_card.column_id }}
                toColumnName: IN PROGRESS
          - name: Check out the source code
            uses: actions/checkout@v2
          - name: 'Populate auth file with SFDX_URL secret'
            shell: bash
            run: 'echo ${{ secrets.AUTH_SECRET}} > ./SFDX_URL_STORE.txt'
          - name: 'Authenticate against dev hub'
            uses: forcedotcom/salesforcedx-actions@master
            with:
              args: 'force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=devhub --setdefaultdevhubusername'
          - name: Create Scratch Org
            uses: forcedotcom/salesforcedx-actions@master
            with:
              args: 'force:org:create --definitionfile=config/project-scratch-def.json --setalias=scratch-org --setdefaultusername'
          - name: Genereate Password
            uses: forcedotcom/salesforcedx-actions@master
            with:
              args: 'force:user:password:generate --targetusername=scratch-org'
          - name: Display user information
            id: display_user
            uses: forcedotcom/salesforcedx-actions@master
            with:
              args: force:user:display --targetusername=scratch-org --json
          - name: install gmail-send
            run: npm install --save gmail-send
            if: steps.check.outputs.isMatch == 'true'
          - name: Give access to email.js file
            run: |
              chmod +x scripts/email.js
          - name: Send Email vi Gmail
            uses: prishanf/sendgrid-action@master
            env:
                DISPLAY_USER_JSON: ${{ steps.display_user.outputs.result }}
                GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
                EMAIL_TO: ${{ secrets.EMAIL_TO }}
                GMAIL_FROM: ${{ secrets.GMAIL_FROM }}
                SCRIPT_FILEPATH: scripts/email.js
            if: steps.check.outputs.isMatch == 'true'
            
