name: Starting a new work item

on:
    project_card:
        types: [moved]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Check move from "TODO" to "IN PROGRESS"
            id: check
            uses: prishanf/salesforcedx-kanban-actions/project_card-check-movement@master
            with:
                token: ${{ secrets.GITHUB_TOKEN}}
                fromColumnId: ${{ github.event.changes.column_id.from }}
                fromColumnName: TODO
                toColumnId: ${{ github.event.project_card.column_id }}
                toColumnName: IN PROGRESS
          - name: Check out the source code
            uses: actions/checkout@v2
          - name: Step 1
            run: echo  ${{ steps.check.outputs.isMatch  }}
            if: steps.check.outputs.isMatch == 'true'
          - name: Step 2
            run: |
              echo ${{ steps.check.outputs.isMatch  }}
              pwd
              ls
              chmod +x scripts/email.js
          - name: Step 3
            run: echo 'Run Step 3' ${{ steps.check.outputs.isMatch  }}
          - name: SendGrid
            uses: prishanf/sendgrid-action@master
            env:
                DISPLAY_USER_JSON: '{"result": {"orgId":"ABC","username":"Prishan","instanceUrl":"www.google.com","loginUrl":"/login"}}'
                DISPLAY_URL_JSON: '{"result": {"url":"/abcd"}}'
                SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
                GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
                EMAIL_TO: ${{ secrets.EMAIL_TO }}
                GMAIL_FROM: ${{ secrets.GMAIL_FROM }}
                SCRIPT_FILEPATH: scripts/email.js
     
            
